version: 2

sources:
  - name: raw_mlb
    description: "MLB raw data loaded from MLB Stats API and Statcast"
    schema: raw_mlb
    tables:
      - name: raw_teams
        description: "MLB team master data (30 active franchises)"
        columns:
          - name: team_id
            description: "Primary key - MLB team ID"
            tests:
              - unique
              - not_null

      - name: raw_players
        description: "MLB player biographical and roster information"
        columns:
          - name: player_id
            description: "Primary key - MLB player ID"
            tests:
              - unique
              - not_null

      - name: raw_games
        description: "MLB game results and box score summaries"
        columns:
          - name: game_pk
            description: "Primary key - unique game identifier"
            tests:
              - unique
              - not_null

      - name: raw_batting_stats
        description: "Season-level batting statistics per player/team/game_type"
        columns:
          - name: id
            description: "Surrogate primary key"
            tests:
              - unique
              - not_null

      - name: raw_pitching_stats
        description: "Season-level pitching statistics per player/team/game_type"
        columns:
          - name: id
            description: "Surrogate primary key"
            tests:
              - unique
              - not_null

      - name: raw_statcast
        description: "Pitch-level Statcast tracking data"
        columns:
          - name: id
            description: "Surrogate primary key"
            tests:
              - unique
              - not_null

      - name: raw_schedule
        description: "MLB game schedule with status and venue information"
        columns:
          - name: id
            description: "Surrogate primary key"
            tests:
              - unique
              - not_null
