with source as (
    select * from {{ source('raw_mlb', 'raw_statcast') }}
),

renamed as (
    select
        id                  as statcast_id,
        game_pk,
        game_date,
        game_year           as season,
        batter              as batter_id,
        pitcher             as pitcher_id,
        batter_name,
        pitcher_name,
        events              as play_result,
        description         as play_description,
        zone                as pitch_zone,
        stand               as batter_side,
        p_throws            as pitcher_throws,
        home_team           as home_team_abbreviation,
        away_team           as away_team_abbreviation,
        type                as pitch_result_type,
        pitch_type          as pitch_type_code,
        pitch_name,
        release_speed,
        release_spin_rate,
        release_extension,
        release_pos_x,
        release_pos_z,
        pfx_x               as horizontal_movement,
        pfx_z               as vertical_movement,
        plate_x,
        plate_z,
        vx0,
        vy0,
        vz0,
        ax,
        ay,
        az,
        sz_top              as strike_zone_top,
        sz_bot              as strike_zone_bottom,
        effective_speed,
        launch_speed        as exit_velocity,
        launch_angle,
        hit_distance_sc     as hit_distance,
        hc_x                as hit_coord_x,
        hc_y                as hit_coord_y,
        estimated_ba_using_speedangle   as expected_batting_avg,
        estimated_woba_using_speedangle as expected_woba,
        babip_value,
        iso_value,
        launch_speed_angle  as launch_speed_angle_bucket,
        at_bat_number,
        pitch_number,
        inning,
        inning_topbot       as inning_half,
        outs_when_up        as outs,
        balls               as ball_count,
        strikes             as strike_count,
        on_1b               as runner_on_1b_id,
        on_2b               as runner_on_2b_id,
        on_3b               as runner_on_3b_id,
        if_fielding_alignment   as infield_alignment,
        of_fielding_alignment   as outfield_alignment,
        loaded_at

    from source
)

select * from renamed
