version: 2

models:
  - name: int_player_season_batting
    description: "Player-level season batting statistics aggregated across teams. Regular season only. Includes calculated wOBA."
    columns:
      - name: player_id
        description: "FK to stg_players"
        tests:
          - not_null
      - name: season
        description: "Season year"
        tests:
          - not_null
      - name: games_played
        description: "Total games played in the season"
      - name: plate_appearances
        description: "Total plate appearances"
      - name: at_bats
        description: "Total at-bats"
      - name: runs
        description: "Runs scored"
      - name: hits
        description: "Base hits"
      - name: doubles
        description: "Doubles"
      - name: triples
        description: "Triples"
      - name: home_runs
        description: "Home runs"
      - name: singles
        description: "Singles (hits - 2B - 3B - HR)"
      - name: rbi
        description: "Runs batted in"
      - name: stolen_bases
        description: "Stolen bases"
      - name: caught_stealing
        description: "Caught stealing"
      - name: walks
        description: "Walks (BB)"
      - name: strikeouts
        description: "Strikeouts"
      - name: hit_by_pitch
        description: "Hit by pitch"
      - name: sacrifice_bunts
        description: "Sacrifice bunts"
      - name: sacrifice_flies
        description: "Sacrifice flies"
      - name: intentional_walks
        description: "Intentional walks"
      - name: total_bases
        description: "Total bases"
      - name: ground_into_double_play
        description: "Grounded into double play"
      - name: batting_average
        description: "Batting average (H/AB)"
      - name: on_base_percentage
        description: "On-base percentage"
      - name: slugging_percentage
        description: "Slugging percentage (TB/AB)"
      - name: on_base_plus_slugging
        description: "OPS (OBP + SLG)"
      - name: woba
        description: "Weighted on-base average using linear weights (0.69*BB + 0.72*HBP + 0.888*1B + 1.271*2B + 1.616*3B + 2.101*HR) / (AB + BB + SF + HBP)"

  - name: int_player_season_pitching
    description: "Player-level season pitching statistics aggregated across teams. Regular season only. Includes calculated FIP."
    columns:
      - name: player_id
        description: "FK to stg_players"
        tests:
          - not_null
      - name: season
        description: "Season year"
        tests:
          - not_null
      - name: wins
        description: "Wins"
      - name: losses
        description: "Losses"
      - name: games
        description: "Games appeared in"
      - name: games_started
        description: "Games started"
      - name: games_finished
        description: "Games finished"
      - name: complete_games
        description: "Complete games"
      - name: shutouts
        description: "Shutouts"
      - name: saves
        description: "Saves"
      - name: save_opportunities
        description: "Save opportunities"
      - name: holds
        description: "Holds"
      - name: blown_saves
        description: "Blown saves"
      - name: innings_pitched
        description: "Innings pitched"
      - name: hits_allowed
        description: "Hits allowed"
      - name: runs_allowed
        description: "Runs allowed"
      - name: earned_runs
        description: "Earned runs"
      - name: home_runs_allowed
        description: "Home runs allowed"
      - name: walks
        description: "Walks issued"
      - name: strikeouts
        description: "Strikeouts"
      - name: hit_batsmen
        description: "Hit batsmen"
      - name: wild_pitches
        description: "Wild pitches"
      - name: balks
        description: "Balks"
      - name: era
        description: "Earned run average (ER * 9 / IP)"
      - name: whip
        description: "Walks plus hits per innings pitched"
      - name: strikeout_walk_ratio
        description: "Strikeout to walk ratio (K/BB)"
      - name: strikeouts_per_9
        description: "Strikeouts per 9 innings"
      - name: walks_per_9
        description: "Walks per 9 innings"
      - name: hits_per_9
        description: "Hits per 9 innings"
      - name: batting_average_against
        description: "Batting average against (approximated)"
      - name: fip
        description: "Fielding Independent Pitching ((13*HR + 3*BB - 2*K) / IP + 3.20)"

  - name: int_game_results
    description: "Game results unpivoted to one row per team per game. Each game produces two rows (home and away). Final games only."
    columns:
      - name: game_pk
        description: "Game identifier"
        tests:
          - not_null
      - name: team_id
        description: "FK to stg_teams - the team this row represents"
        tests:
          - not_null
      - name: opponent_id
        description: "FK to stg_teams - the opposing team"
        tests:
          - not_null
      - name: game_type
        description: "Game type (R=Regular, P=Postseason, etc.)"
      - name: season
        description: "Season year"
        tests:
          - not_null
      - name: game_date
        description: "Date of the game"
        tests:
          - not_null
      - name: is_home
        description: "Whether this team was the home team"
        tests:
          - not_null
      - name: runs_scored
        description: "Runs scored by this team"
      - name: runs_allowed
        description: "Runs allowed by this team"
      - name: is_win
        description: "Whether this team won"
        tests:
          - not_null
      - name: is_loss
        description: "Whether this team lost"
        tests:
          - not_null

  - name: int_team_standings
    description: "Team standings by season with win/loss record, win percentage, and games behind division leader. Regular season only."
    columns:
      - name: team_id
        description: "FK to stg_teams"
        tests:
          - not_null
      - name: season
        description: "Season year"
        tests:
          - not_null
      - name: team_full_name
        description: "Full team name"
      - name: team_abbreviation
        description: "Team abbreviation"
      - name: league_name
        description: "League (AL/NL)"
      - name: division_name
        description: "Division (e.g., AL East)"
      - name: games_played
        description: "Total games played"
      - name: wins
        description: "Total wins"
      - name: losses
        description: "Total losses"
      - name: win_pct
        description: "Winning percentage"
      - name: runs_scored
        description: "Total runs scored"
      - name: runs_allowed
        description: "Total runs allowed"
      - name: run_differential
        description: "Run differential (RS - RA)"
      - name: home_wins
        description: "Home wins"
      - name: home_losses
        description: "Home losses"
      - name: away_wins
        description: "Away wins"
      - name: away_losses
        description: "Away losses"
      - name: games_behind
        description: "Games behind division leader"

  - name: int_statcast_metrics
    description: "Aggregated Statcast batted-ball metrics per player per season. Contains both batter and pitcher perspectives (identified by player_role)."
    columns:
      - name: player_id
        description: "FK to stg_players"
        tests:
          - not_null
      - name: season
        description: "Season year"
        tests:
          - not_null
      - name: player_role
        description: "Role perspective: 'batter' or 'pitcher'"
        tests:
          - not_null
          - accepted_values:
              values: ['batter', 'pitcher']
      - name: total_batted_balls
        description: "Total batted ball events"
      - name: barrels
        description: "Barrel count (EV >= 98 mph AND LA between 26-30 degrees)"
      - name: barrel_pct
        description: "Barrel percentage"
      - name: hard_hits
        description: "Hard-hit ball count (EV >= 95 mph)"
      - name: hard_hit_pct
        description: "Hard-hit percentage"
      - name: avg_exit_velocity
        description: "Average exit velocity (mph)"
      - name: avg_launch_angle
        description: "Average launch angle (degrees)"
      - name: max_exit_velocity
        description: "Maximum exit velocity (mph)"
      - name: avg_expected_batting_avg
        description: "Average xBA"
      - name: avg_expected_woba
        description: "Average xwOBA"
